### ISSUE TITLE
一点点小小的建议

### ISSUE THREAD

**Issue by BillZhou233** [CytoidCommunity/Cytoid-wiki#2]
首先是 iOS 上右下角按键的图标错位问题，一时半会没找到合适的解决方法，我在自己的分支里的处理方法是直接把悬浮按键调成透明的，这样最起码看起来正常些...

然后看了下代码高亮的组件，或许应该要把 Json 的组件加上，这样在解说故事板相关内容的时候应该观感会好些。然后插件里面有个代码复制的，可以考虑加上。

Fork 过来之后把框架改得一团糟... 就不用 PR 力（

**Comment by Teages** [comment]
透明的恐怕挺丑(

json的代码高亮没有吗, 估计是要单独加载插件, 待会补上

**Comment by BillZhou233** [comment]
个人觉得透明的还行... 至少板子上看着没错位比较舒服（busji

**Comment by Teages** [comment]
你能不能交个pr, 我看看怎么合并? 
懒了((((

**Comment by BillZhou233** [comment]
改的东西太多了，CDN 优化的时候做了一大堆适配，最近还在调简繁转换器... 而且回家拿到板子之后发现在上面还有大量 Bug 要修（

**Comment by Teages** [comment]
没事, 先交上来, 我慢慢合并上

**Comment by Teages** [comment]
这几天不写谱就搞这个

**Comment by BillZhou233** [comment]
仓库在学校电脑，还有东西没交，人在家里（

**Comment by BillZhou233** [comment]
基本把移动端各种 Bug 修掉了，等明天去学校之后再用那边电脑写入仓库。

另外，我的分支里面填了 Gameplay 部分的条目坑，如果需要的话可以先看下有什么问题我再改改（

**Comment by Teages** [comment]
jao, 正好没写这个

**Comment by BillZhou233** [comment]
各种补丁打完了（大概），但是整理下发现太乱了真的一团糟...

不然我先把 Gameplay 那几篇打包私发给你看下

**Comment by Teages** [comment]
不必，我合并时也只是参考重写

**Comment by BillZhou233** [comment]
行吧我先去 Codeforces（（
